FROM node:lts-slim as base

WORKDIR /code
ENV PATH /code/node_modules/.bin:$PATH

COPY ./package*.json ./
RUN npm install
COPY ./ ./

FROM base as dev
EXPOSE 3000
ENV NODE_ENV development
CMD ["npm", "run", "dev"]

# FROM Base as Test
# ENV NODE_ENV test
# RUN npm run test
